name: Branch Name Validation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
      
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          
          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix|hotfix|refactor)/[a-z0-9-]+$ ]]; then
            echo "Erreur : Le nom de la branche ne respecte pas les conventions."
            echo "Format attendu : feature/123-description ou bugfix/456-description"
            echo "Nom de branche actuel : $BRANCH_NAME"
            exit 1
          fi