name: Build and Test

on:
  push:
    branches: [ feature/*,bugfix/*,hotfix/*,refactor/* ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Étape 2 : Configurer JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    # Étape 3 : Construire le projet avec Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # Étape 4 : Exécuter les tests unitaires
    - name: Run tests
      run: mvn test
    
    # Étape 5 : Générer un rapport de couverture de code avec JaCoCo
    - name: Generate JaCoCo Coverage Report
      run: mvn jacoco:report
    
    # Étape 6 : Sauvegarder les artefacts générés (fichiers .jar)
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: target/*.jar