name: Code Quality

on:
  push:
    branches: [ feature/*,bugfix/*,hotfix/*,refactor/* ]
  pull_request:
    branches: [ develop, main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Run Checkstyle
      run: mvn checkstyle:check
      
    - name: Run SpotBugs
      run: mvn spotbugs:check
      
    - name: Generate SpotBugs report (if failure)
      if: failure()
      run: mvn spotbugs:gui
      
    - name: Upload quality reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          target/site/checkstyle.html
          target/spotbugsXml.xml
        retention-days: 5